### ISSUE TITLE
Issue on any app except Tik Tok

### ISSUE THREAD

**Issue by P3ntestGuy** [iiheng/VCAMSX#2]
Hi,

This tool works perfectly on TikTok but when i have attempted to use this on another application i am seeing this in Logcat:

Failed to find provider info for com.wangyiheng.vcamsx.preferences

Could you help with this?

**Comment by P3ntestGuy** [comment]
In face i get 4 errors when using another app as the target:

![image](https://github.com/iiheng/VCAMSX/assets/117677248/a02cc845-720a-4639-aa13-8053e808c0a1)

Any help you can give would be amazing

**Comment by P3ntestGuy** [comment]
This was on a Pixel 4 API33

**Comment by daigualaile** [comment]
This software primarily relies on the service provider. If intercepted, its functionality would likely be compromised, as on the Android platform, each application operates within a sandboxed environment, ensuring non-shared content. Therefore, it is imperative to investigate the nature of this issue.
