### ISSUE TITLE
“隐藏应用列表”隐藏Xposed模块，抖音、TikTok  黑屏无法显示画面

### ISSUE THREAD

**Issue by vipxiaoma** [iiheng/VCAMSX#8]
手机：一加   安卓10

“隐藏应用列表”隐藏Xposed模块，抖音、TikTok  黑屏无法显示画面！

能否修复一下，避免APP检查环境发现Xposed相关模块

**Comment by vipxiaoma** [comment]
直播会拾取真实麦克风声音+虚拟视频声音混合

**Comment by daigualaile** [comment]
目前隐藏应用列表，会把模块给屏蔽了，导致获取不到信息，因为宿主的视频数据都是从模块拿的，模块被屏蔽了，就拿不到，所以会导致黑屏。直播的话你可以看看内录头，这个应该会屏蔽麦克风的声音
